# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.24'
  displayName: 'Install Terraform 0.12.24'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'terraform'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/Terraform'
    backendServiceArm: 'EXP-QA-Terraform-DevOps'
    backendAzureRmResourceGroupName: 'EXP-QA-Terraform-DevOps'
    backendAzureRmStorageAccountName: 'expqatformlabstore'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/Terraform'
    environmentServiceNameAzureRM: 'EXP-QA-Terraform-DevOps'