name: Cancel stale runs

env:
  minutes: 60
on:
  workflow_dispatch:
  schedule:
    - cron: "1,31 * * * *"

jobs:
  checkforruns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - id: ghlogin 
      #   shell: bash
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login  --with-token
      - name: Run cancel action
        id: cancelstale
        uses: ./.github/actions/cancelstaleruns
        with:
          OlderThan: ${{env.minutes}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show result count
        run: echo "Cancelled ${{ steps.cancelstale.outputs.count-cancelled }} runs"
      - name: Clean up my old runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
        with:
          repository: ${{ github.repository }}
          workflow: ${{ github.workflow }}
          status: 'completed'
          maximum-workflow-runs-to-keep: 12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
          

