name: Cancel stale runs and delete old runs

env:
  minutes: 60
on:
  workflow_dispatch:
  schedule:
    - cron: "31 2 * * *"

jobs:
  checkforruns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - id: ghlogin 
      #   shell: bash
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login  --with-token
      - name: Run cancel action
        id: cancelstale
        uses: ./.github/actions/cancelstaleruns
        with:
          OlderThan: ${{env.minutes}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show result count
        run: echo "Cancelled ${{ steps.cancelstale.outputs.count-cancelled }} runs"
      - name: Clean up my old runs
        uses: mwigginsdev/delete-oldest-workflow-runs@v1
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 12
          workflow_name: ${{ github.workflow }}
          
          
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
