name: Cancel stale runs
on:
  workflow_dispatch:
  schedule:
    - cron: "1,31 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      minutes: 60
    steps:
      - uses: actions/checkout@v2
      - id: ghlogin 
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login  --with-token
      - name: Run cancel action
        id: cancelstale
        uses: ./.github/actions/cancelstaleruns
        with:
          OlderThan: 60
      - name: Show result count
        run: echo "Cancelled ${{ steps.cancelstale.outputs.count-cancelled }} runs"
          

